export const WIZARD_CLASS_ADVANCEMENT_CONFIG = [
  {
    level: 1,
    feature: "施法，奥术回想",
    knownTrickNum: 3,
    spellSlotsNum: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    feature: "选择奥术传承",
    knownTrickNum: 3,
    spellSlotsNum: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    feature: "－",
    knownTrickNum: 3,
    spellSlotsNum: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    feature: "属性值提升",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    feature: "－",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    feature: "奥术传承特性",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    feature: "－",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    feature: "属性值提升",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    feature: "－",
    knownTrickNum: 4,
    spellSlotsNum: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    feature: "奥术传承特性",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    feature: "－",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    feature: "属性值提升",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    feature: "－",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    feature: "奥术传承特性",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    feature: "－",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    feature: "属性值提升",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    feature: "－",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    feature: "法术精通",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    feature: "属性值提升",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    feature: "独门法术",
    knownTrickNum: 5,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
