export const BARD_CLASS_ADVANCEMENT_CONFIG = [
  {
    level: 1,
    feature: "施法，诗人激励(d6)",
    knownTrickNum: 2,
    knownSpellNum: 4,
    spellSlotsNum: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    feature: "万事通，休憩曲(d6)",
    knownTrickNum: 2,
    knownSpellNum: 5,
    spellSlotsNum: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    feature: "选择诗人学院，专精",
    knownTrickNum: 2,
    knownSpellNum: 6,
    spellSlotsNum: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    feature: "属性值提升",
    knownTrickNum: 3,
    knownSpellNum: 7,
    spellSlotsNum: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    feature: "诗人激励(d8)，激励之源",
    knownTrickNum: 3,
    knownSpellNum: 8,
    spellSlotsNum: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    feature: "反迷惑，学院特性",
    knownTrickNum: 3,
    knownSpellNum: 9,
    spellSlotsNum: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    feature: "－",
    knownTrickNum: 3,
    knownSpellNum: 10,
    spellSlotsNum: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    feature: "属性值提升",
    knownTrickNum: 3,
    knownSpellNum: 11,
    spellSlotsNum: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    feature: "休憩曲(d8)",
    knownTrickNum: 3,
    knownSpellNum: 12,
    spellSlotsNum: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    feature: "诗人激励(d10)，专精，魔法奥秘",
    knownTrickNum: 4,
    knownSpellNum: 14,
    spellSlotsNum: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    feature: "－",
    knownTrickNum: 4,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    feature: "休憩曲(d10)",
    knownTrickNum: 4,
    knownSpellNum: 16,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    feature: "魔法奥秘，学院特性",
    knownTrickNum: 4,
    knownSpellNum: 18,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    feature: "诗人激励(d12)",
    knownTrickNum: 4,
    knownSpellNum: 19,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 19,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    feature: "休憩曲(d12)",
    knownTrickNum: 4,
    knownSpellNum: 20,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    feature: "魔法奥秘",
    knownTrickNum: 4,
    knownSpellNum: 22,
    spellSlotsNum: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 22,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    feature: "先发激励",
    knownTrickNum: 4,
    knownSpellNum: 22,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
