export const SORCERER_CLASS_ADVANCEMENT_CONFIG = [
  {
    level: 1,
    sorceryPointNum: 0,
    feature: "施法，术法起源",
    knownTrickNum: 4,
    knownSpellNum: 2,
    spellSlotsNum: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    sorceryPointNum: 2,
    feature: "魔力泉涌",
    knownTrickNum: 4,
    knownSpellNum: 3,
    spellSlotsNum: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    sorceryPointNum: 3,
    feature: "超魔法",
    knownTrickNum: 4,
    knownSpellNum: 4,
    spellSlotsNum: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    sorceryPointNum: 4,
    feature: "属性值提升",
    knownTrickNum: 5,
    knownSpellNum: 5,
    spellSlotsNum: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    sorceryPointNum: 5,
    feature: "－",
    knownTrickNum: 5,
    knownSpellNum: 6,
    spellSlotsNum: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    sorceryPointNum: 6,
    feature: "术法起源特性",
    knownTrickNum: 5,
    knownSpellNum: 7,
    spellSlotsNum: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    sorceryPointNum: 7,
    feature: "－",
    knownTrickNum: 5,
    knownSpellNum: 8,
    spellSlotsNum: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    sorceryPointNum: 8,
    feature: "属性值提升",
    knownTrickNum: 5,
    knownSpellNum: 9,
    spellSlotsNum: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    sorceryPointNum: 9,
    feature: "－",
    knownTrickNum: 5,
    knownSpellNum: 10,
    spellSlotsNum: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    sorceryPointNum: 10,
    feature: "超魔法",
    knownTrickNum: 6,
    knownSpellNum: 11,
    spellSlotsNum: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    sorceryPointNum: 11,
    feature: "－",
    knownTrickNum: 6,
    knownSpellNum: 12,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    sorceryPointNum: 12,
    feature: "属性值提升",
    knownTrickNum: 6,
    knownSpellNum: 12,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    sorceryPointNum: 13,
    feature: "－",
    knownTrickNum: 6,
    knownSpellNum: 13,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    sorceryPointNum: 14,
    feature: "术法起源特性",
    knownTrickNum: 6,
    knownSpellNum: 13,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    sorceryPointNum: 15,
    feature: "－",
    knownTrickNum: 6,
    knownSpellNum: 14,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    sorceryPointNum: 16,
    feature: "属性值提升",
    knownTrickNum: 6,
    knownSpellNum: 14,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    sorceryPointNum: 17,
    feature: "超魔法",
    knownTrickNum: 6,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    sorceryPointNum: 18,
    feature: "术法起源特性",
    knownTrickNum: 6,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    sorceryPointNum: 19,
    feature: "属性值提升",
    knownTrickNum: 6,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    sorceryPointNum: 20,
    feature: "术法复苏",
    knownTrickNum: 6,
    knownSpellNum: 15,
    spellSlotsNum: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
