export const WARLOCK_CLASS_ADVANCEMENT_CONFIG = [
  {
    level: 1,
    feature: "选择异界宗主，契约魔法",
    knownTrickNum: 2,
    knownSpellNum: 2,
    spellSlotsNum: [1, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    feature: "魔能祈唤",
    knownTrickNum: 2,
    knownSpellNum: 3,
    spellSlotsNum: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    feature: "契约之赐",
    knownTrickNum: 2,
    knownSpellNum: 4,
    spellSlotsNum: [0, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    feature: "属性值提升",
    knownTrickNum: 3,
    knownSpellNum: 5,
    spellSlotsNum: [0, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    feature: "－",
    knownTrickNum: 3,
    knownSpellNum: 6,
    spellSlotsNum: [0, 0, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    feature: "异界宗主特性",
    knownTrickNum: 3,
    knownSpellNum: 7,
    spellSlotsNum: [0, 0, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    feature: "－",
    knownTrickNum: 3,
    knownSpellNum: 8,
    spellSlotsNum: [0, 0, 0, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    feature: "属性值提升",
    knownTrickNum: 3,
    knownSpellNum: 9,
    spellSlotsNum: [0, 0, 0, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    feature: "－",
    knownTrickNum: 3,
    knownSpellNum: 10,
    spellSlotsNum: [0, 0, 0, 0, 2, 0, 0, 0, 0],
  },
  {
    level: 10,
    feature: "异界宗主特性",
    knownTrickNum: 4,
    knownSpellNum: 10,
    spellSlotsNum: [0, 0, 0, 0, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    feature: "玄奥秘法（6 环）",
    knownTrickNum: 4,
    knownSpellNum: 11,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 12,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 11,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 13,
    feature: "玄奥秘法（7 环）",
    knownTrickNum: 4,
    knownSpellNum: 12,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 14,
    feature: "异界宗主特性",
    knownTrickNum: 4,
    knownSpellNum: 12,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 15,
    feature: "玄奥秘法（8 环）",
    knownTrickNum: 4,
    knownSpellNum: 13,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 16,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 13,
    spellSlotsNum: [0, 0, 0, 0, 3, 0, 0, 0, 0],
  },
  {
    level: 17,
    feature: "玄奥秘法（9 环）",
    knownTrickNum: 4,
    knownSpellNum: 14,
    spellSlotsNum: [0, 0, 0, 0, 4, 0, 0, 0, 0],
  },
  {
    level: 18,
    feature: "术法起源特性",
    knownTrickNum: 4,
    knownSpellNum: 14,
    spellSlotsNum: [0, 0, 0, 0, 4, 0, 0, 0, 0],
  },
  {
    level: 19,
    feature: "属性值提升",
    knownTrickNum: 4,
    knownSpellNum: 15,
    spellSlotsNum: [0, 0, 0, 0, 4, 0, 0, 0, 0],
  },
  {
    level: 20,
    feature: "魔能掌控",
    knownTrickNum: 4,
    knownSpellNum: 15,
    spellSlotsNum: [0, 0, 0, 0, 4, 0, 0, 0, 0],
  },
];
